# Generated by Django 4.1.2 on 2024-02-13 01:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mrtr.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=2)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager_meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, validators=[mrtr.models.validate_date])),
                ('location', models.CharField(max_length=50)),
                ('attendees', models.TextField(blank=True)),
                ('ongoing_issues', models.TextField(blank=True)),
                ('new_issues', models.TextField(blank=True)),
                ('minutes_discussed', models.BooleanField()),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=10, validators=[mrtr.models.validate_phone])),
                ('email', models.EmailField(blank=True, max_length=62)),
                ('admit_date', models.DateField(default=django.utils.timezone.now)),
                ('rent', models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(1000)])),
                ('door_code', models.CharField(blank=True, max_length=4)),
                ('referral_info', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('bed', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrtr.bed')),
            ],
        ),
        migrations.CreateModel(
            name='Shopping_trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, validators=[mrtr.models.validate_date])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('notes', models.TextField(blank=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, validators=[mrtr.models.validate_date])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('type', models.CharField(blank=True, max_length=30)),
                ('method', models.CharField(blank=True, max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrtr.resident')),
            ],
        ),
        migrations.CreateModel(
            name='Supply_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.TextField(blank=True)),
                ('other', models.CharField(blank=True, max_length=50)),
                ('fulfilled', models.BooleanField(default=False)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrtr.house')),
                ('manager', models.ForeignKey(blank=True, db_column='manager_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='mrtr.resident')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrtr.shopping_trip')),
            ],
        ),
        migrations.CreateModel(
            name='Site_visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, validators=[mrtr.models.validate_date])),
                ('issues', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrtr.house')),
                ('manager', models.ForeignKey(blank=True, db_column='manager_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='mrtr.resident')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField()),
                ('fulfilled', models.BooleanField(default=False)),
                ('fulfillment_date', models.DateField(null=True)),
                ('fulfillment_notes', models.TextField(blank=True)),
                ('fulfillment_cost', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrtr.house')),
                ('manager', models.ForeignKey(blank=True, db_column='manager_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='mrtr.resident')),
            ],
        ),
        migrations.CreateModel(
            name='House_meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, validators=[mrtr.models.validate_date])),
                ('issues', models.TextField()),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrtr.house')),
                ('manager', models.ForeignKey(blank=True, db_column='manager_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='mrtr.resident')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='manager',
            field=models.ForeignKey(blank=True, db_column='manager_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='mrtr.resident'),
        ),
        migrations.CreateModel(
            name='Drug_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, validators=[mrtr.models.validate_date])),
                ('result', models.CharField(choices=[('Negative', 'Negative'), ('Positive', 'Positive'), ('Positive (Meds)', 'Positive (Meds)'), ('Invalid', 'Invalid'), ('Other (Specify)', 'Other (Specify)')], max_length=17)),
                ('substances', models.TextField(blank=True)),
                ('notes', models.CharField(blank=True, max_length=50)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('manager', models.ForeignKey(blank=True, db_column='manager_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dt_manager', to='mrtr.resident')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrtr.resident')),
            ],
        ),
        migrations.CreateModel(
            name='Check_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, validators=[mrtr.models.validate_date])),
                ('method', models.CharField(choices=[('In person', 'In person'), ('Phone call', 'Phone call'), ('Text', 'Text')], max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('manager', models.ForeignKey(blank=True, db_column='manager_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ci_manager', to='mrtr.resident')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrtr.resident')),
            ],
        ),
        migrations.AddField(
            model_name='bed',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrtr.house'),
        ),
        migrations.CreateModel(
            name='Absentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrtr.house_meeting')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrtr.resident')),
            ],
        ),
    ]
