# Generated by Django 4.1.2 on 2023-03-18 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrtr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Check_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('ip', 'In person'), ('pc', 'Phone call'), ('tx', 'Text')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Drug_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('neg', 'Negative'), ('pos', 'Positive'), ('med', 'Positive (meds)'), ('inv', 'Invalid'), ('oth', 'Other (specify)')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='House_manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='House_meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Manager_issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('n', 'New'), ('o', 'Ongoing')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager_meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('minutes_discussed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Rent_change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mrtr.bed')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mrtr.house')),
            ],
        ),
        migrations.CreateModel(
            name='Shopping_trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site_visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Supply_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('ppt', 'Paper towels'), ('tpp', 'Toilet paper'), ('ldt', 'Laundry detergent'), ('diw', 'Disinfectant wipes'), ('kgb', 'Garbage bags - kitchen'), ('ygb', 'Garbage bags - yard'), ('dso', 'Dish soap'), ('dwd', 'Dishwashing detergent'), ('dsp', 'Dish sponges'), ('glc', 'Glass cleaner'), ('apc', 'All-purpose cleaner'), ('spb', 'Spray bottle'), ('swp', 'Swiffer pads'), ('sst', 'Sheet set - twin'), ('ssf', 'Sheet set - full'), ('cmt', 'Comforter - twin'), ('cmf', 'Comforter - full'), ('plw', 'Pillow'), ('sol', 'Sign-out logs'), ('vil', 'Visitor logs'), ('ilr', 'Itinerary/leave request forms'), ('bmd', 'B Mod Forms'), ('ech', 'Meds/emergency contact sheets'), ('uak', 'UA kits'), ('oth', 'Other (specify')], max_length=3, null=True)),
                ('other', models.CharField(max_length=50, null=True)),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rnt', 'Rent charge'), ('rfd', 'Refund'), ('inc', 'Sober incentive'), ('nra', 'New rent amount adjustment'), ('fee', 'Assess fee'), ('lon', 'Loan (will pay back)'), ('pmt', 'Rent payment'), ('bon', 'Bonus'), ('wrk', 'Work/reimbursement'), ('sos', "Sober support (won't pay back)"), ('fix', 'Balance fix'), ('oth', 'Other adjustment (specify)')], max_length=3)),
                ('method', models.CharField(choices=[('ach', 'ACH'), ('csh', 'Cash'), ('cap', 'Cash App'), ('chk', 'Check'), ('mod', 'Money order'), ('ppl', 'PayPal'), ('vnm', 'Venmo'), ('zel', 'Zelle'), ('oth', 'Other (specify)')], max_length=3, null=True)),
                ('notes', models.TextField(null=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mrtr.resident')),
            ],
        ),
        migrations.DeleteModel(
            name='exampleUser',
        ),
        migrations.AddField(
            model_name='bed',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mrtr.house'),
        ),
    ]
