# Generated by Django 4.1.2 on 2023-03-25 20:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrtr', '0003_remove_resident_bed_bed_resident'),
    ]

    operations = [
        migrations.DeleteModel(
            name='House_manager',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='resident',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='house',
        ),
        migrations.AddField(
            model_name='absentee',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mrtr.house_meeting'),
        ),
        migrations.AddField(
            model_name='absentee',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mrtr.resident'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='manager',
            field=models.ForeignKey(blank=True, db_column='manager_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='mrtr.resident'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mrtr.manager_meeting'),
        ),
        migrations.AddField(
            model_name='bed',
            name='name',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='check_in',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='check_in',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='check_in',
            name='manager',
            field=models.ForeignKey(blank=True, db_column='manager_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manager', to='mrtr.resident'),
        ),
        migrations.AddField(
            model_name='check_in',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='check_in',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mrtr.resident'),
        ),
        migrations.AddField(
            model_name='check_in',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drug_test',
            name='amphetamines',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drug_test',
            name='barbiturates',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drug_test',
            name='benzodiazepines',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drug_test',
            name='cocaine',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drug_test',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drug_test',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='drug_test',
            name='marijuana',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drug_test',
            name='opiates',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drug_test',
            name='other',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drug_test',
            name='phencyclidine',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drug_test',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mrtr.resident'),
        ),
        migrations.AddField(
            model_name='drug_test',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='manager',
            field=models.ForeignKey(db_column='manager_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='mrtr.resident'),
        ),
        migrations.AddField(
            model_name='house_meeting',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house_meeting',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mrtr.house'),
        ),
        migrations.AddField(
            model_name='house_meeting',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='house_meeting',
            name='manager',
            field=models.ForeignKey(blank=True, db_column='manager_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='mrtr.resident'),
        ),
        migrations.AddField(
            model_name='house_meeting',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manager_issue',
            name='expected_completion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manager_issue',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='manager_issue',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mrtr.manager_meeting'),
        ),
        migrations.AddField(
            model_name='manager_issue',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manager_meeting',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manager_meeting',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='manager_meeting',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rent_change',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rent_change',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rent_change',
            name='new',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='rent_change',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rent_change',
            name='old',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='rent_change',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mrtr.resident'),
        ),
        migrations.AddField(
            model_name='rent_change',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='admit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='bed',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mrtr.bed'),
        ),
        migrations.AddField(
            model_name='resident',
            name='discharge_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='door_code',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AddField(
            model_name='resident',
            name='email',
            field=models.EmailField(max_length=62, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='phone',
            field=models.BigIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AddField(
            model_name='resident',
            name='referral_info',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='rent',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='resident',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopping_trip',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='shopping_trip',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site_visit',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site_visit',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mrtr.house'),
        ),
        migrations.AddField(
            model_name='site_visit',
            name='issues',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='site_visit',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='site_visit',
            name='manager',
            field=models.ForeignKey(blank=True, db_column='manager_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='mrtr.resident'),
        ),
        migrations.AddField(
            model_name='site_visit',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supply_request',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supply_request',
            name='fulfilled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supply_request',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mrtr.house'),
        ),
        migrations.AddField(
            model_name='supply_request',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='supply_request',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mrtr.shopping_trip'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mrtr.resident'),
        ),
    ]
