# Generated by Django 4.1.2 on 2023-06-19 04:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mrtr', '0007_alter_resident_first_name_alter_resident_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='house_meeting',
            name='house',
        ),
        migrations.RemoveField(
            model_name='house_meeting',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='manager_issue',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='rent_change',
            name='resident',
        ),
        migrations.RemoveField(
            model_name='site_visit',
            name='house',
        ),
        migrations.RemoveField(
            model_name='site_visit',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='supply_request',
            name='house',
        ),
        migrations.RemoveField(
            model_name='supply_request',
            name='trip',
        ),
        migrations.AddField(
            model_name='house',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bed',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrtr.house'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='name',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='check_in',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='check_in',
            name='manager',
            field=models.ForeignKey(db_column='manager_id', on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='mrtr.resident'),
        ),
        migrations.AlterField(
            model_name='check_in',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrtr.resident'),
        ),
        migrations.AlterField(
            model_name='check_in',
            name='submission_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='drug_test',
            name='amphetamines',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='drug_test',
            name='barbiturates',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='drug_test',
            name='benzodiazepines',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='drug_test',
            name='cocaine',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='drug_test',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='drug_test',
            name='marijuana',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='drug_test',
            name='opiates',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='drug_test',
            name='phencyclidine',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='drug_test',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrtr.resident'),
        ),
        migrations.AlterField(
            model_name='drug_test',
            name='submission_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='house',
            name='manager',
            field=models.ForeignKey(db_column='manager_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='mrtr.resident'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='admit_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='resident',
            name='bed',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrtr.bed'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resident',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resident',
            name='rent',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='resident',
            name='submission_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.CharField(blank=True, choices=[('ach', 'ACH'), ('csh', 'Cash'), ('cap', 'Cash App'), ('chk', 'Check'), ('mod', 'Money order'), ('ppl', 'PayPal'), ('vnm', 'Venmo'), ('zel', 'Zelle'), ('oth', 'Other (specify)'), ('', '')], max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrtr.resident'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='submission_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, choices=[('pmt', 'Rent payment'), ('fee', 'Fee'), ('oth', 'Other adjustment (specify)')], max_length=3),
        ),
        migrations.DeleteModel(
            name='Absentee',
        ),
        migrations.DeleteModel(
            name='Attendee',
        ),
        migrations.DeleteModel(
            name='House_meeting',
        ),
        migrations.DeleteModel(
            name='Manager_issue',
        ),
        migrations.DeleteModel(
            name='Manager_meeting',
        ),
        migrations.DeleteModel(
            name='Rent_change',
        ),
        migrations.DeleteModel(
            name='Shopping_trip',
        ),
        migrations.DeleteModel(
            name='Site_visit',
        ),
        migrations.DeleteModel(
            name='Supply_request',
        ),
    ]
