# Generated by Django 4.1.2 on 2023-06-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrtr', '0008_remove_attendee_manager_remove_attendee_meeting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug_test',
            name='resident',
        ),
        migrations.AddField(
            model_name='house',
            name='address',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='city',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='state',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, choices=[('rnt', 'Rent charge'), ('pmt', 'Rent payment'), ('fee', 'Fee'), ('oth', 'Other adjustment (specify)')], max_length=3),
        ),
        migrations.DeleteModel(
            name='Check_in',
        ),
        migrations.DeleteModel(
            name='Drug_test',
        ),
    ]
