# Generated by Django 4.1.2 on 2023-06-24 22:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mrtr', '0009_remove_drug_test_resident_house_address_house_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager_meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issues', models.TextField(null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=50)),
                ('minutes_discussed', models.BooleanField()),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrtr.resident')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrtr.manager_meeting')),
            ],
        ),
    ]
