# Generated by Django 4.1.2 on 2023-06-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrtr', '0010_manager_meeting_attendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager_meeting',
            name='title',
            field=models.TextField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
