# Generated by Django 4.1.2 on 2023-06-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrtr', '0011_manager_meeting_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager_meeting',
            name='attendee',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='manager_meeting',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='Attendee',
        ),
    ]
