# Generated by Django 4.1.2 on 2023-06-28 00:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mrtr', '0012_manager_meeting_attendee_alter_manager_meeting_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping_trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supply_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.CharField(choices=[('ppt', 'Paper towels'), ('tpp', 'Toilet paper'), ('ldt', 'Laundry detergent'), ('diw', 'Disinfectant wipes'), ('kgb', 'Garbage bags - kitchen'), ('ygb', 'Garbage bags - yard'), ('dso', 'Dish soap'), ('dwd', 'Dishwashing detergent'), ('dsp', 'Dish sponges'), ('glc', 'Glass cleaner'), ('apc', 'All-purpose cleaner'), ('spb', 'Spray bottle'), ('swp', 'Swiffer pads'), ('sst', 'Sheet set - twin'), ('ssf', 'Sheet set - full'), ('cmt', 'Comforter - twin'), ('cmf', 'Comforter - full'), ('plw', 'Pillow'), ('sol', 'Sign-out logs'), ('vil', 'Visitor logs'), ('ilr', 'Itinerary/leave request forms'), ('bmd', 'B Mod Forms'), ('ech', 'Meds/emergency contact sheets'), ('uak', 'UA kits'), ('oth', 'Other (specify')], max_length=3, null=True)),
                ('other', models.CharField(max_length=50, null=True)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(null=True)),
                ('fulfilled', models.BooleanField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrtr.house')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrtr.shopping_trip')),
            ],
        ),
    ]
