# Generated by Django 4.1.2 on 2023-07-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrtr', '0014_alter_transaction_method_alter_transaction_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply_request',
            name='trip',
        ),
        migrations.AlterField(
            model_name='supply_request',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supply_request',
            name='other',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
