# Generated by Django 4.1.2 on 2023-07-28 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrtr', '0015_remove_supply_request_trip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply_request',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrtr.shopping_trip'),
        ),
    ]
