# Generated by Django 4.1.2 on 2023-07-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrtr', '0016_supply_request_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply_request',
            name='add',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
