# Generated by Django 4.1.2 on 2023-03-22 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrtr', '0002_absentee_attendee_bed_check_in_drug_test_house_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='bed',
        ),
        migrations.AddField(
            model_name='bed',
            name='resident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mrtr.resident'),
        ),
    ]
