# Generated by Django 4.1.2 on 2023-03-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrtr', '0004_delete_house_manager_remove_bed_resident_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resident',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
