# Generated by Django 4.1.2 on 2023-03-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrtr', '0005_alter_resident_first_name_alter_resident_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
