# Generated by Django 4.1.2 on 2023-07-22 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrtr', '0014_alter_transaction_method_alter_transaction_type_and_more'),
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assoc_resident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mrtr.resident'),
        ),
    ]
